package c_negocio.a_relacional;
// Generated 2/02/2017 03:59:54 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Ciclo generated by hbm2java
 */
public class Ciclo  implements java.io.Serializable {


     private CicloId id;
     private Proyecto proyecto;
     private Date FInicio;
     private Date FFin;
     private Set partes = new HashSet(0);
     private Set fases = new HashSet(0);
     private Set rlCls = new HashSet(0);

    public Ciclo() {
    }

	
    public Ciclo(CicloId id, Proyecto proyecto, Date FInicio) {
        this.id = id;
        this.proyecto = proyecto;
        this.FInicio = FInicio;
    }
    public Ciclo(CicloId id, Proyecto proyecto, Date FInicio, Date FFin, Set partes, Set fases, Set rlCls) {
       this.id = id;
       this.proyecto = proyecto;
       this.FInicio = FInicio;
       this.FFin = FFin;
       this.partes = partes;
       this.fases = fases;
       this.rlCls = rlCls;
    }
   
    public CicloId getId() {
        return this.id;
    }
    
    public void setId(CicloId id) {
        this.id = id;
    }
    public Proyecto getProyecto() {
        return this.proyecto;
    }
    
    public void setProyecto(Proyecto proyecto) {
        this.proyecto = proyecto;
    }
    public Date getFInicio() {
        return this.FInicio;
    }
    
    public void setFInicio(Date FInicio) {
        this.FInicio = FInicio;
    }
    public Date getFFin() {
        return this.FFin;
    }
    
    public void setFFin(Date FFin) {
        this.FFin = FFin;
    }
    public Set getPartes() {
        return this.partes;
    }
    
    public void setPartes(Set partes) {
        this.partes = partes;
    }
    public Set getFases() {
        return this.fases;
    }
    
    public void setFases(Set fases) {
        this.fases = fases;
    }
    public Set getRlCls() {
        return this.rlCls;
    }
    
    public void setRlCls(Set rlCls) {
        this.rlCls = rlCls;
    }




}


