package c_negocio.a_relacional;
// Generated Jan 28, 2017 1:24:51 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Criterio generated by hbm2java
 */
public class Criterio  implements java.io.Serializable {


     private String nombre;
     private String descripcion;
     private String tipo;
     private Set pyCrs = new HashSet(0);

    public Criterio() {
    }

	
    public Criterio(String nombre, String tipo) {
        this.nombre = nombre;
        this.tipo = tipo;
    }
    public Criterio(String nombre, String descripcion, String tipo, Set pyCrs) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.tipo = tipo;
       this.pyCrs = pyCrs;
    }
   
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Set getPyCrs() {
        return this.pyCrs;
    }
    
    public void setPyCrs(Set pyCrs) {
        this.pyCrs = pyCrs;
    }




}


