package c_negocio.a_relacional;
// Generated 2/02/2017 03:59:54 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Fase generated by hbm2java
 */
public class Fase  implements java.io.Serializable {


     private FaseId id;
     private Ciclo ciclo;
     private Date FInicio;
     private Date FFin;

    public Fase() {
    }

	
    public Fase(FaseId id, Ciclo ciclo, Date FInicio) {
        this.id = id;
        this.ciclo = ciclo;
        this.FInicio = FInicio;
    }
    public Fase(FaseId id, Ciclo ciclo, Date FInicio, Date FFin) {
       this.id = id;
       this.ciclo = ciclo;
       this.FInicio = FInicio;
       this.FFin = FFin;
    }
   
    public FaseId getId() {
        return this.id;
    }
    
    public void setId(FaseId id) {
        this.id = id;
    }
    public Ciclo getCiclo() {
        return this.ciclo;
    }
    
    public void setCiclo(Ciclo ciclo) {
        this.ciclo = ciclo;
    }
    public Date getFInicio() {
        return this.FInicio;
    }
    
    public void setFInicio(Date FInicio) {
        this.FInicio = FInicio;
    }
    public Date getFFin() {
        return this.FFin;
    }
    
    public void setFFin(Date FFin) {
        this.FFin = FFin;
    }




}


