package c_negocio.a_relacional;
// Generated Jan 28, 2017 1:24:51 PM by Hibernate Tools 4.3.1



/**
 * MetaId generated by hbm2java
 */
public class MetaId  implements java.io.Serializable {


     private String rol;
     private String usuario;
     private String descripcion;
     private String proyecto;
     private byte NCiclo;

    public MetaId() {
    }
    
    /**
     * Editado manualmente para las metas definidas por la metodología
     * @param descripcion 
     */
    public MetaId(String descripcion){
        this.descripcion = descripcion;
    }
    
    public MetaId(String descripcion, String rol){
        this.descripcion = descripcion;
        this.rol = rol;
    }

    public MetaId(String rol, String usuario, String descripcion, String proyecto, byte NCiclo) {
       this.rol = rol;
       this.usuario = usuario;
       this.descripcion = descripcion;
       this.proyecto = proyecto;
       this.NCiclo = NCiclo;
    }
   
    public String getRol() {
        return this.rol;
    }
    
    public void setRol(String rol) {
        this.rol = rol;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getProyecto() {
        return this.proyecto;
    }
    
    public void setProyecto(String proyecto) {
        this.proyecto = proyecto;
    }
    public byte getNCiclo() {
        return this.NCiclo;
    }
    
    public void setNCiclo(byte NCiclo) {
        this.NCiclo = NCiclo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MetaId) ) return false;
		 MetaId castOther = ( MetaId ) other; 
         
		 return ( (this.getRol()==castOther.getRol()) || ( this.getRol()!=null && castOther.getRol()!=null && this.getRol().equals(castOther.getRol()) ) )
 && ( (this.getUsuario()==castOther.getUsuario()) || ( this.getUsuario()!=null && castOther.getUsuario()!=null && this.getUsuario().equals(castOther.getUsuario()) ) )
 && ( (this.getDescripcion()==castOther.getDescripcion()) || ( this.getDescripcion()!=null && castOther.getDescripcion()!=null && this.getDescripcion().equals(castOther.getDescripcion()) ) )
 && ( (this.getProyecto()==castOther.getProyecto()) || ( this.getProyecto()!=null && castOther.getProyecto()!=null && this.getProyecto().equals(castOther.getProyecto()) ) )
 && (this.getNCiclo()==castOther.getNCiclo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getRol() == null ? 0 : this.getRol().hashCode() );
         result = 37 * result + ( getUsuario() == null ? 0 : this.getUsuario().hashCode() );
         result = 37 * result + ( getDescripcion() == null ? 0 : this.getDescripcion().hashCode() );
         result = 37 * result + ( getProyecto() == null ? 0 : this.getProyecto().hashCode() );
         result = 37 * result + this.getNCiclo();
         return result;
   }   


}


