package c_negocio.a_relacional;
// Generated Jan 28, 2017 1:24:51 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Meta generated by hbm2java
 */
public class Meta  implements java.io.Serializable {


     private MetaId id;
     private RlCl rlCl;
     private Boolean lograda;
     private String observacion;
     private boolean automatica;
     private String tipo;
     private Date fechaCreacion;
     private BigDecimal valor;
     private String unidadValor;
     private String comparativaValor;

    public Meta() {
    }
    
    /**
     * Editado manualmente para las metas definidas por la metodología
     * @param id
     * @param automatica
     * @param valor
     * @param unidadValor
     * @param comparativaValor 
     */
    public Meta(MetaId id, boolean automatica, BigDecimal valor, String unidadValor, String comparativaValor){
        this.id = id;
        this.automatica = automatica;
        this.valor = valor;
        this.unidadValor = unidadValor;
        this.comparativaValor = comparativaValor;
    }
    
    public Meta(MetaId id, boolean automatica){
        this.id = id;
        this.automatica = automatica;
    }

	
    public Meta(MetaId id, RlCl rlCl, boolean automatica, String tipo, Date fechaCreacion) {
        this.id = id;
        this.rlCl = rlCl;
        this.automatica = automatica;
        this.tipo = tipo;
        this.fechaCreacion = fechaCreacion;
    }
    public Meta(MetaId id, RlCl rlCl, Boolean lograda, String observacion, boolean automatica, String tipo, Date fechaCreacion, BigDecimal valor, String unidadValor, String comparativaValor) {
       this.id = id;
       this.rlCl = rlCl;
       this.lograda = lograda;
       this.observacion = observacion;
       this.automatica = automatica;
       this.tipo = tipo;
       this.fechaCreacion = fechaCreacion;
       this.valor = valor;
       this.unidadValor = unidadValor;
       this.comparativaValor = comparativaValor;
    }
   
    public MetaId getId() {
        return this.id;
    }
    
    public void setId(MetaId id) {
        this.id = id;
    }
    public RlCl getRlCl() {
        return this.rlCl;
    }
    
    public void setRlCl(RlCl rlCl) {
        this.rlCl = rlCl;
    }

    public Boolean getLograda() {
        return this.lograda;
    }
    
    public void setLograda(Boolean lograda) {
        this.lograda = lograda;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public boolean isAutomatica() {
        return this.automatica;
    }
    
    public void setAutomatica(boolean automatica) {
        this.automatica = automatica;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public BigDecimal getValor() {
        return this.valor;
    }
    
    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }
    public String getUnidadValor() {
        return this.unidadValor;
    }
    
    public void setUnidadValor(String unidadValor) {
        this.unidadValor = unidadValor;
    }
    public String getComparativaValor() {
        return this.comparativaValor;
    }
    
    public void setComparativaValor(String comparativaValor) {
        this.comparativaValor = comparativaValor;
    }




}


