package c_negocio.a_relacional;
// Generated 2/02/2017 03:59:54 PM by Hibernate Tools 4.3.1



/**
 * Opciontsp generated by hbm2java
 */
public class Opciontsp  implements java.io.Serializable {


     private String nombre;
     private String tipo;

    public Opciontsp() {
    }

    public Opciontsp(String nombre, String tipo) {
       this.nombre = nombre;
       this.tipo = tipo;
    }
   
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }




}


