package c_negocio.a_relacional;
// Generated Jan 28, 2017 1:24:51 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Parte generated by hbm2java
 */
public class Parte  implements java.io.Serializable {


     private int id;
     private Ciclo ciclo;
     private Parte parte;
     private String nombre;
     private String descripcion;
     private String tipo;
     private String estado;
     private String observacion;
     private Set partes = new HashSet(0);

    public Parte() {
    }

	
    public Parte(int id, Ciclo ciclo, String nombre, String descripcion, String tipo, String estado) {
        this.id = id;
        this.ciclo = ciclo;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.tipo = tipo;
        this.estado = estado;
    }
    public Parte(int id, Ciclo ciclo, Parte parte, String nombre, String descripcion, String tipo, String estado, String observacion, Set partes) {
       this.id = id;
       this.ciclo = ciclo;
       this.parte = parte;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.tipo = tipo;
       this.estado = estado;
       this.observacion = observacion;
       this.partes = partes;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Ciclo getCiclo() {
        return this.ciclo;
    }
    
    public void setCiclo(Ciclo ciclo) {
        this.ciclo = ciclo;
    }
    public Parte getParte() {
        return this.parte;
    }
    
    public void setParte(Parte parte) {
        this.parte = parte;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public Set getPartes() {
        return this.partes;
    }
    
    public void setPartes(Set partes) {
        this.partes = partes;
    }




}


