package c_negocio.a_relacional;
// Generated Jan 28, 2017 1:24:51 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Proyecto generated by hbm2java
 */
public class Proyecto  implements java.io.Serializable {


     private String nombre;
     private Usuario usuario;
     private String descripcion;
     private Date FInicio;
     private Date FFin;
     private Byte cicloActual;
     private String faseActual;
     private short NCiclos;
     private Date FEstFin;
     private String urlImg;
     private Set ciclos = new HashSet(0);
     private Set pyCrs = new HashSet(0);

    public Proyecto() {
    }

	
    public Proyecto(String nombre, Usuario usuario, String descripcion, Date FInicio, short NCiclos, Date FEstFin, String urlImg) {
        this.nombre = nombre;
        this.usuario = usuario;
        this.descripcion = descripcion;
        this.FInicio = FInicio;
        this.NCiclos = NCiclos;
        this.FEstFin = FEstFin;
        this.urlImg = urlImg;
    }
    public Proyecto(String nombre, Usuario usuario, String descripcion, Date FInicio, Date FFin, Byte cicloActual, String faseActual, short NCiclos, Date FEstFin, String urlImg, Set ciclos, Set pyCrs) {
       this.nombre = nombre;
       this.usuario = usuario;
       this.descripcion = descripcion;
       this.FInicio = FInicio;
       this.FFin = FFin;
       this.cicloActual = cicloActual;
       this.faseActual = faseActual;
       this.NCiclos = NCiclos;
       this.FEstFin = FEstFin;
       this.urlImg = urlImg;
       this.ciclos = ciclos;
       this.pyCrs = pyCrs;
    }
   
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFInicio() {
        return this.FInicio;
    }
    
    public void setFInicio(Date FInicio) {
        this.FInicio = FInicio;
    }
    public Date getFFin() {
        return this.FFin;
    }
    
    public void setFFin(Date FFin) {
        this.FFin = FFin;
    }
    public Byte getCicloActual() {
        return this.cicloActual;
    }
    
    public void setCicloActual(Byte cicloActual) {
        this.cicloActual = cicloActual;
    }
    public String getFaseActual() {
        return this.faseActual;
    }
    
    public void setFaseActual(String faseActual) {
        this.faseActual = faseActual;
    }
    public short getNCiclos() {
        return this.NCiclos;
    }
    
    public void setNCiclos(short NCiclos) {
        this.NCiclos = NCiclos;
    }
    public Date getFEstFin() {
        return this.FEstFin;
    }
    
    public void setFEstFin(Date FEstFin) {
        this.FEstFin = FEstFin;
    }
    public String getUrlImg() {
        return this.urlImg;
    }
    
    public void setUrlImg(String urlImg) {
        this.urlImg = urlImg;
    }
    public Set getCiclos() {
        return this.ciclos;
    }
    
    public void setCiclos(Set ciclos) {
        this.ciclos = ciclos;
    }
    public Set getPyCrs() {
        return this.pyCrs;
    }
    
    public void setPyCrs(Set pyCrs) {
        this.pyCrs = pyCrs;
    }




}


