package c_negocio.a_relacional;
// Generated Jan 28, 2017 1:24:51 PM by Hibernate Tools 4.3.1



/**
 * PyCr generated by hbm2java
 */
public class PyCr  implements java.io.Serializable {


     private PyCrId id;
     private Criterio criterio;
     private Proyecto proyecto;
     private String valor;

    public PyCr() {
    }

    public PyCr(PyCrId id, Criterio criterio, Proyecto proyecto, String valor) {
       this.id = id;
       this.criterio = criterio;
       this.proyecto = proyecto;
       this.valor = valor;
    }
   
    public PyCrId getId() {
        return this.id;
    }
    
    public void setId(PyCrId id) {
        this.id = id;
    }
    public Criterio getCriterio() {
        return this.criterio;
    }
    
    public void setCriterio(Criterio criterio) {
        this.criterio = criterio;
    }
    public Proyecto getProyecto() {
        return this.proyecto;
    }
    
    public void setProyecto(Proyecto proyecto) {
        this.proyecto = proyecto;
    }
    public String getValor() {
        return this.valor;
    }
    
    public void setValor(String valor) {
        this.valor = valor;
    }




}


