package c_negocio.a_relacional;
// Generated Jan 28, 2017 1:24:51 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * RlCl generated by hbm2java
 */
public class RlCl  implements java.io.Serializable {


     private RlClId id;
     private Ciclo ciclo;
     private Rol rol;
     private Usuario usuario;
     private String estado;
     private String observacion;
     private Set documentos = new HashSet(0);
     private Set metas = new HashSet(0);

    public RlCl() {
    }

	
    public RlCl(RlClId id, Ciclo ciclo, Rol rol, Usuario usuario, String estado) {
        this.id = id;
        this.ciclo = ciclo;
        this.rol = rol;
        this.usuario = usuario;
        this.estado = estado;
    }
    public RlCl(RlClId id, Ciclo ciclo, Rol rol, Usuario usuario, String estado, String observacion, Set documentos, Set metas) {
       this.id = id;
       this.ciclo = ciclo;
       this.rol = rol;
       this.usuario = usuario;
       this.estado = estado;
       this.observacion = observacion;
       this.documentos = documentos;
       this.metas = metas;
    }
   
    public RlClId getId() {
        return this.id;
    }
    
    public void setId(RlClId id) {
        this.id = id;
    }
    public Ciclo getCiclo() {
        return this.ciclo;
    }
    
    public void setCiclo(Ciclo ciclo) {
        this.ciclo = ciclo;
    }
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public Set getDocumentos() {
        return this.documentos;
    }
    
    public void setDocumentos(Set documentos) {
        this.documentos = documentos;
    }
    public Set getMetas() {
        return this.metas;
    }
    
    public void setMetas(Set metas) {
        this.metas = metas;
    }




}


