package c_negocio.a_relacional;
// Generated Jan 28, 2017 1:24:51 PM by Hibernate Tools 4.3.1



/**
 * RlClId generated by hbm2java
 */
public class RlClId  implements java.io.Serializable {


     private byte NCiclo;
     private String proyecto;
     private String usuario;
     private String rol;

    public RlClId() {
    }

    public RlClId(byte NCiclo, String proyecto, String usuario, String rol) {
       this.NCiclo = NCiclo;
       this.proyecto = proyecto;
       this.usuario = usuario;
       this.rol = rol;
    }
   
    public byte getNCiclo() {
        return this.NCiclo;
    }
    
    public void setNCiclo(byte NCiclo) {
        this.NCiclo = NCiclo;
    }
    public String getProyecto() {
        return this.proyecto;
    }
    
    public void setProyecto(String proyecto) {
        this.proyecto = proyecto;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getRol() {
        return this.rol;
    }
    
    public void setRol(String rol) {
        this.rol = rol;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RlClId) ) return false;
		 RlClId castOther = ( RlClId ) other; 
         
		 return (this.getNCiclo()==castOther.getNCiclo())
 && ( (this.getProyecto()==castOther.getProyecto()) || ( this.getProyecto()!=null && castOther.getProyecto()!=null && this.getProyecto().equals(castOther.getProyecto()) ) )
 && ( (this.getUsuario()==castOther.getUsuario()) || ( this.getUsuario()!=null && castOther.getUsuario()!=null && this.getUsuario().equals(castOther.getUsuario()) ) )
 && ( (this.getRol()==castOther.getRol()) || ( this.getRol()!=null && castOther.getRol()!=null && this.getRol().equals(castOther.getRol()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getNCiclo();
         result = 37 * result + ( getProyecto() == null ? 0 : this.getProyecto().hashCode() );
         result = 37 * result + ( getUsuario() == null ? 0 : this.getUsuario().hashCode() );
         result = 37 * result + ( getRol() == null ? 0 : this.getRol().hashCode() );
         return result;
   }   


}


