package c_negocio.a_relacional;
// Generated Jan 28, 2017 1:24:51 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Rol generated by hbm2java
 */
public class Rol  implements java.io.Serializable {


     private String nombre;
     private String descripcion;
     private Set rlCls = new HashSet(0);

    public Rol() {
    }

	
    public Rol(String nombre, String descripcion) {
        this.nombre = nombre;
        this.descripcion = descripcion;
    }
    public Rol(String nombre, String descripcion, Set rlCls) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.rlCls = rlCls;
    }
   
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getRlCls() {
        return this.rlCls;
    }
    
    public void setRlCls(Set rlCls) {
        this.rlCls = rlCls;
    }




}


